// Generated by LiveScript 1.3.1
(function(){
  var _, fs, argv;
  _ = require('underscore');
  fs = require('fs');
  argv = process.argv;
  argv.shift();
  argv.shift();
  console.log('files', argv);
  _.map(argv, function(file){
    var data, matched;
    console.log("reading", file);
    data = fs.readFileSync(file);
    matched = String(data).match(/'(.*?)'|"(.*?)"/g);
    matched = _.map(matched, function(m){
      m = m.replace(/\"/g, '');
      return m = m.replace(/\'/g, '');
    });
    return _.each(matched, function(m){
      return process.stdout.write("'" + m + "',");
    });
  });
}).call(this);
